### ISSUE TITLE
Boundaries and constraints for free moving objects

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#23]
@zepumph 
For the following, please refer to this figure:

![Slide1](https://user-images.githubusercontent.com/5109055/79689848-40680a00-820c-11ea-9281-3b32a22740aa.jpeg)

- Please add a *short thick black line* at the top and bottom of the screen, aligned with the starting locations for *each* of the free moving objects. The result would be two black lines on the top of the sim screen, and two black lines on the bottom of the sim screen. 
- Please add *invisible* constraints to the y-direction motion. (See vertical dashed lines in the figure). 

Note - the figure shows the tall "boxes" where each free moving object can move to be quite narrow in the y-direction. This can be wider... I'm not trying to overly constrain the learner, it's just a limitation of the artwork. :) We'll probably want to tweak the width/height of the black lines and the range of the y-direction once you have something implemented. We'll want it to look and feel "right", so consider my artwork to be a simple sketch rather than exact specification.

**Comment by zepumph** [comment]
Implemented above. I moved the layout of the control elements to try to maximize the width of the draggable pieces of the proportion. Here is a screenshot! Let me know what you think.

![image](https://user-images.githubusercontent.com/6856943/79797524-dd599e80-8303-11ea-910e-994c261c772b.png)

**Comment by emily-phet** [comment]
@zepumph Please half the size of each black bar and the corresponding y-axis movement.

**Comment by zepumph** [comment]
Each "ratio half" used to be 4/9's width of the sim. I made if 1/4 width. I think it looked better, and was easier to manage layout in quarters. How does that look?

![Uploading image.png…]()

**Comment by emily-phet** [comment]
@zepumph Can you increase the horizontal distance (maybe doubling) the white space between each "ratio half"?

Also, you probably are aware, but the version from phettest today has the region within which I can move each hand out of alignment with the drawn grid lines. Movement space seems offset to the left of the drawn grid lines.

**Comment by zepumph** [comment]
horizontal distance increased above. I also fixed the dragging/alignment bug. There is still a tiny bit of movement, especially when using other pointers. I'll take a look soon.

**Comment by emily-phet** [comment]
@zepumph The sim needs the following:

- To have grid lines numbered from 0-10 (currently 0-9)
- To have the zero line start just atop the bottom thick black bars, and to have the "10" line line up with the maximum position of the hand (where the center of the hand at its highest position just "touches" the number 10 line). 
- Decrease the thickness (height) of the thick black bars by ~20%
- Have the thick black bars disappear whenever *any* gridlines are present ("grid" or "numbered grid").

**Comment by zepumph** [comment]
Please review!

**Comment by emily-phet** [comment]
@zepumph 

- [ ] The gridlines still appear to be numbered 0-9 to me (on phettest). Please add the "10" on the top line.

- [ ] Also - can you bring back the horizontal-lines-only grid? I just see horizontal+vertical grid on default, and no other grid options in the options menu...

- [ ] Last, there needs to be a line at 0. Please make this line be at the same place that would be the very top of the black bars when no grid is shown.

**Comment by zepumph** [comment]
>The gridlines still appear to be numbered 0-9 to me (on phettest). Please add the "10" on the top line.

In my local copy the "10" appears, but I can't get it to show on phettest. Weird! I'll look into it further. 

> Also - can you bring back the horizontal-lines-only grid? I just see horizontal+vertical grid on default, and no other grid options in the options menu...

I don't feel like I have clear instructions here. Do you want the "Grid" radio button to turn into two radio buttons: "Horizontal" (just horizontal) and "Grid" (both)? Do you want vertical lines possible at all in the sim? 

The way it is implemented currently did not allow for a separate vertical line visible toggle, which is why that wasn't in the design options dialog. I can easily do that, but I didn't want to needlessly refactor until there was a desire. This is a place though where it would be nice (and cheaper) to know the direction we are heading as much as possible before implementing anything else. 

Thought?

**Comment by zepumph** [comment]
For some reason, after manually pulling RaP on phettest, the "10" is now showing for me. I cleaned up the unit code a bit above, over to @emily-phet for design condiserations about UI for horizontal vs vertical lines.

**Comment by emily-phet** [comment]
@zepumph Thanks!
Regarding grid lines, for now just remove the vertical lines altogether from the visual. This is the simplest visual, and I'd like to move forward with that, and only bring in vertical lines if we find a really compelling reason to do so. So, we may want to switch to "horizontal+vertical only" in the future, but for now, let's proceed with "horizontal only". Other than a situation where we want to try out both,
